FileNotFoundError in line 6 of /home/cf/Sandbox/Finngen/LiftOver/LiftDownFinngen.smk:
[Errno 2] No such file or directory: 'finn_ids_test.txt'
  File "/home/cf/Sandbox/Finngen/LiftOver/LiftDownFinngen.smk", line 6, in <module>
  File "/home/cf/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 689, in read_table
  File "/home/cf/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 462, in _read
  File "/home/cf/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 819, in __init__
  File "/home/cf/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
  File "/home/cf/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1867, in __init__
  File "/home/cf/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1368, in _open_handles
  File "/home/cf/anaconda3/lib/python3.7/site-packages/pandas/io/common.py", line 647, in get_handle
